[project]
name = "dpm-prototype"
version = "0.1.0"
description = "Prototype DPM lookup service and ingestion pipeline"
requires-python = ">=3.10"

[project.dependencies]
fastapi = "*"
uvicorn = {extras = ["standard"], version = "*"}
sqlmodel = "*"
python-dotenv = "*"
pandas = "*"
requests = "*"